version: '3'
services:
  frontend:
    container_name: app_client
    build: ./client
    ports:
      - 8080:8080
    platform: linux/x86_64
    working_dir: /client
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:8080" ]
      timeout: 20s
      retries: 5
  backend:
    container_name: app_server
    build: ./server
    ports:
      - 3001:3001
    platform: linux/x86_64
    working_dir: /server
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=cashforce_v3
      - DB_HOST=db
      - DB_PORT=3306
      - DIALECT=mysql
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 20s
      retries: 5
    command: sh -c "npm run build && npm run db:reset"
  db:
    image: mysql:8.0.21
    container_name: db
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5
    cap_add:
      - SYS_NICE
